### ISSUE TITLE
基于ChatGLM2的RLHF训练问题

### ISSUE THREAD

**Issue by wydy1601** [sunzeyeah/RLHF#23]
[2023-08-12 01:22:11,409] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.10.0, git-hash=unknown, git-branch=unknown
Traceback (most recent call last):
  File "/root/inpc_projects/ChatGLM-6B/rlhf_again/src/train_rlhf.py", line 373, in <module>
    main()
  File "/root/inpc_projects/ChatGLM-6B/rlhf_again/src/train_rlhf.py", line 237, in main
    rlhf_engine = DeepSpeedRLHFEngine(
  File "/root/inpc_projects/ChatGLM-6B/rlhf_again/src/models/rlhf_engine.py", line 146, in __init__
    self.ref = self._init_ref(
  File "/root/inpc_projects/ChatGLM-6B/rlhf_again/src/models/rlhf_engine.py", line 245, in _init_ref
    ref_engine, *_ = deepspeed.initialize(model=ref_model,
  File "/root/anaconda3/envs/rlhf/lib/python3.10/site-packages/deepspeed/__init__.py", line 157, in initialize
    config_class = DeepSpeedConfig(config, mpu)
  File "/root/anaconda3/envs/rlhf/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 769, in __init__
    self._configure_train_batch_size()
  File "/root/anaconda3/envs/rlhf/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 942, in _configure_train_batch_size
    self._batch_assertion()
  File "/root/anaconda3/envs/rlhf/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 890, in _batch_assertion
    assert train_batch == micro_batch * grad_acc * self.world_size, (
AssertionError: Check batch related parameters. train_batch_size is not equal to micro_batch_per_gpu * gradient_acc_step * world_size 1024 != 4 * 1 * 8

在使用ChatGLM2作为sft和reward模型，在A100*8的环境上训练的时候，在第三阶段train_rlhf时出现如上报错，尝试了很多方法都没有解决，deepspeed版本是0.10.0，想请问一下作者有什么建议吗？

**Comment by sunzeyeah** [comment]
这个原因应该是系统认为在运行```deepspeed.initialize()```之前```world_size```一直都是1，所以```ds_config['train_batch_size']```不需要乘上```world_size```。只能在运行```deepspeed.initialize()```之前，才把```ds_config['train_batch_size']```改为乘上```world_size```。

RL部分的代码还没来得及修复这个问题，具体可以参见[pretrain_wo_trainer.py 第220-221行](https://github.com/sunzeyeah/RLHF/blob/master/src/pretrain_wo_trainer.py#L220-L221)和[pretrain_wo_trainer.py 第292行](https://github.com/sunzeyeah/RLHF/blob/master/src/pretrain_wo_trainer.py#L292)

**Comment by 18780165950** [comment]
> 这个原因应该是系统认为在运行`deepspeed.initialize()`之前`world_size`一直都是1，所以`ds_config['train_batch_size']`不需要乘上`world_size`。只能在运行`deepspeed.initialize()`之前，才把`ds_config['train_batch_size']`改为乘上`world_size`。
> 
> RL部分的代码还没来得及修复这个问题，具体可以参见[pretrain_wo_trainer.py 第220-221行](https://github.com/sunzeyeah/RLHF/blob/master/src/pretrain_wo_trainer.py#L220-L221)和[pretrain_wo_trainer.py 第292行](https://github.com/sunzeyeah/RLHF/blob/master/src/pretrain_wo_trainer.py#L292)
具体咋解决呢
